appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: r10tpvV7G3s/qJnDxXHjzYztDpTrE2mNO3osJS/ibqx03aSF3cdrQosxrq/sm58dWBdUoeHpgA8IZMv0H3uh7IFzU8Urxs19CES5gEDm/qbRHOK4nGNfqC5sI+QA7l1mKXqDZvRQdbRmUJVuSNheUmrVYy40Lgop/gXK1COjJtS8l8iVLHj5UlvlbHDTUf5iyvl/VI98OthqjdihwOm44z7PnVdv9TUij0G0x8JlB3vd4ftYIGJ1wRe7rWrC71YTyWIO7+M2o5drWt1y3gvv/PJNY+VxioImvZqt46vYK1xkmbZ8unerX8LNRMgYp9IlrJh5tz1lIeN3kLxB4R3TmYjNYWjfUCGYWLRED7AA6lSAM4baEdwoanYeqMXEKdjS36B46bHGi8coKtkh95pX45BRla9vetoawf6SDdDdiPTsvAO4u7N8dbJJFQxgCXO2WcJVUEGIIOvbq71FyR5D7QfUgJLcw9Gg32mUIoMBhlmJenUkbSmh5LYz9Yrx8T/gaCHw1NXuqmP8v+F8VKitBPXUUd8aprg5r7SBmjBUamK2F0QsO+gSp6Wf0CBy+4i3am35FANdu5LkYfWeYiL7s8Gf0zzC/Hgd34AewpoY7O73za9+cMtAFilLox518yGK2OQA/BoIBID3nk2Dm9VtHYMl4hexqlfS0fb4XmENK2A=
